// ========================= DROSv2 License preamble===========================
// Software for DROSv2 is covered jointly under GPLv3 and Boost 1.0 licenses,
// to the extent required by included Boost sources and GPL sources, and to the
// more restrictive case pertaining thereunto, as defined herebelow. Beyond those
// requirements, any code not explicitly restricted by either of thowse two license
// models shall be deemed to be licensed under the GPLv3 license and subject to
// those restrictions.
//
// Copyright 2012, Virginia Tech, University of New Mexico, and Christopher Wolfe
//
// ========================= Boost License ====================================
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
// =============================== GPL V3 ====================================
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

#include "DataFormat.h"

DataFormat::FormatList DataFormat::knownFormats = map_list_of
	("DEFAULT_DRX",  DataFormat("DRX_GENERIC",  4128ll,  79014048ll, PT_DRX,     -1 ))
	("DEFAULT_TBN",  DataFormat("DEFAULT_TBN",  1048ll, 117440512ll, PT_TBN,     -1 ))
	("DEFAULT_TBW",  DataFormat("DEFAULT_TBW",  1224ll,  42991616ll, PT_TBW,     -1 ))

	("TBN_FILT_1",   DataFormat("TBN_FILT_1",   1048ll,   1064375ll, PT_TBN, 196000 ))
	("TBN_FILT_2",   DataFormat("TBN_FILT_2",   1048ll,   3326172ll, PT_TBN,  62720 ))
	("TBN_FILT_3",   DataFormat("TBN_FILT_3",   1048ll,   6652344ll, PT_TBN,  31360 ))
	("TBN_FILT_4",   DataFormat("TBN_FILT_4",   1048ll,  13304688ll, PT_TBN,  15680 ))
	("TBN_FILT_5",   DataFormat("TBN_FILT_5",   1048ll,  26609375ll, PT_TBN,   7840 ))
	("TBN_FILT_6",   DataFormat("TBN_FILT_6",   1048ll,  53218750ll, PT_TBN,   3920 ))
	("TBN_FILT_7",   DataFormat("TBN_FILT_7",   1048ll, 106437500ll, PT_TBN,   1960 ))

	("DRX_FILT_1",   DataFormat("DRX_FILT_1",   4128ll,   1011360ll, PT_DRX,    784 ))
	("DRX_FILT_2",   DataFormat("DRX_FILT_2",   4128ll,   2018592ll, PT_DRX,    392 ))
	("DRX_FILT_3",   DataFormat("DRX_FILT_3",   4128ll,   4033056ll, PT_DRX,    196 ))
	("DRX_FILT_4",   DataFormat("DRX_FILT_4",   4128ll,   8066112ll, PT_DRX,     98 ))
	("DRX_FILT_5",   DataFormat("DRX_FILT_5",   4128ll,  16128096ll, PT_DRX,     49 ))
	("DRX_FILT_6",   DataFormat("DRX_FILT_6",   4128ll,  39509088ll, PT_DRX,     20 ))
	("DRX_FILT_7",   DataFormat("DRX_FILT_7",   4128ll,  79014048ll, PT_DRX,     10 ))

	("20DIPOLE_TBW", DataFormat("20DIPOLE_TBW", 1224ll,   7549632ll, PT_TBN,     -1 ))
	("20DIPOLE_TBN", DataFormat("20DIPOLE_TBN", 1048ll,   4194304ll, PT_TBW,     -1 ))

;
const string DataFormat::defaultFormatName = "DRX_FILT_7";

INIT_ACCESS_MUTEX_ST(DataFormat);




