name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Software Install - Ubuntu"
        run: |
          sudo apt-get install -y \
            build-essential \
            ca-certificates \
            coreutils \
            curl \
            git \
            gpg \
            gpgv \
            gzip \
            libboost-all-dev \
            libfftw3-dev \
            libgdbm-dev \
            pkg-config \
            software-properties-common
      - uses: actions/checkout@v3
      - name: "Build - Single Instance"
        run: |
          make all
      - name: "Build - Multiple Instances"
        run: |
           make clean
           ./build_helper.py 1 2 
